feat: cicd

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -46,15 +46,27 @@ jobs:
           SSH_HOST: ${{ secrets.SSH_HOST }}
           SSH_USER: ${{ secrets.SSH_USER }}
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          KEY_FILE: a2cd.key # 不能用~/.ssh/a2cd.key作为value
+          HOST_KEY: a2cd # 不能用~/.ssh/a2cd.key作为value
         run: |
-          mkdir -p ~/.ssh/ && echo "$SSH_PRIVATE_KEY" > ~/.ssh/$KEY_FILE && chmod 600 ~/.ssh/$KEY_FILE
+          mkdir -p ~/.ssh/ && echo "$SSH_PRIVATE_KEY" > ~/.ssh/$HOST_KEY.pri.key && chmod 600 ~/.ssh/$HOST_KEY.pri.key
           cat >> ~/.ssh/config <<END
-          Host a2cd
+          Host $HOST_KEY
             HostName $SSH_HOST
             User $SSH_USER
-            IdentityFile ~/.ssh/$KEY_FILE
+            IdentityFile ~/.ssh/$HOST_KEY.pri.key
             StrictHostKeyChecking no
           END
+      - name: Run git pull
+        # 从github pull代码，失败重试3次
+        run: |
+          ssh a2cd "cd /usr/local/repo/ja-hello-world/ && \
+                    git pull origin main || \
+                    (echo 'git pull retry: 1/3' && git pull origin main) || \
+                    (echo 'git pull retry: 2/3' && git pull origin main) || \
+                    (echo 'git pull retry: 3/3' && git pull origin main) || \
+                    (echo 'git pull failed' && exit 1)"
       - name: Run deploy
-        run: ssh a2cd 'cd /usr/local/repo/ja-hello-world/ && git pull origin main && docker-compose pull && docker-compose up -d'
+        run: |
+          ssh a2cd "cd /usr/local/repo/ja-hello-world/ && \
+                    docker-compose pull && \
+                    docker-compose up -d"
